# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.


# @param {String} s
# @param {String} t
# @return {Character}
def find_the_difference(s, t)
    hash = Hash.new(0)
    n = s.size
    (0..n).each do |i|
        hash[s[i]] += 1
        hash[t[i]] += 1
    end
    hash[t[n+1]] += 1
    hash.each do |key, value|
        return key if value%2 != 0
   end
end